/** REG_DESC part A (split for MCP push size). */
import type { RegDesc } from './modbusProtocolParams'
export const REG_DESC_A: Record<number, RegDesc> = {

  // ── Config 0x00-0x0A ────────────────────────
  0x0000: { name: 'AC Input Low-V Cutout',   group: 'AC Config',  scale: 0.1,  unit: 'V' },
  0x0001: { name: 'AC Input Low-V Restore',   group: 'AC Config',  scale: 0.1,  unit: 'V' },
  0x0002: { name: 'AC Input High-V Cutout',   group: 'AC Config',  scale: 0.1,  unit: 'V' },
  0x0003: { name: 'AC Input High-V Restore',   group: 'AC Config',  scale: 0.1,  unit: 'V' },
  0x0004: { name: 'AC Freq Low Cutout',     group: 'AC Config',  scale: 0.1,  unit: 'Hz' },
  0x0005: { name: 'AC Freq Low Restore',     group: 'AC Config',  scale: 0.1,  unit: 'Hz' },
  0x0006: { name: 'AC Freq High Cutout',     group: 'AC Config',  scale: 0.1,  unit: 'Hz' },
  0x0007: { name: 'AC Freq High Restore',     group: 'AC Config',  scale: 0.1,  unit: 'Hz' },
  0x0008: { name: 'Inverter Output Voltage',   group: 'AC Config',  scale: 0.1,  unit: 'V' },
  0x0009: { name: 'AC Bypass Output Power',     group: 'AC Config',  scale: 1,    unit: 'W' },
  0x000A: { name: 'AC Inverter Output Power',     group: 'AC Config',  scale: 1,    unit: 'W' },
  // ── Config 0x10-0x1F ────────────────────────
  0x0010: { name: 'Cell Low-V Alarm',       group: 'Battery Config', scale: 1,   unit: 'mV' },
  0x0011: { name: 'Cell Low-V Shutdown',       group: 'Battery Config', scale: 1,   unit: 'mV' },
  0x0012: { name: 'Cell Low-V Alarm Restore',   group: 'Battery Config', scale: 1,   unit: 'mV' },
  0x0013: { name: 'Cell High-V Alarm',       group: 'Battery Config', scale: 1,   unit: 'mV' },
  0x0014: { name: 'Cell High-V Alarm Restore',   group: 'Battery Config', scale: 1,   unit: 'mV' },
  0x0015: { name: 'Cell Low-Temp Protect',       group: 'Battery Config', scale: 1,   unit: '℃', signed: true },
  0x0016: { name: 'Cell Low-Temp Alarm',       group: 'Battery Config', scale: 1,   unit: '℃', signed: true },
  0x0017: { name: 'Cell Low-Temp Alarm Restore',   group: 'Battery Config', scale: 1,   unit: '℃', signed: true },
  0x0018: { name: 'Cell High-Temp Protect',       group: 'Battery Config', scale: 1,   unit: '℃', signed: true },
  0x0019: { name: 'Cell High-Temp Alarm',       group: 'Battery Config', scale: 1,   unit: '℃', signed: true },
  0x001A: { name: 'Cell High-Temp Alarm Restore',   group: 'Battery Config', scale: 1,   unit: '℃', signed: true },
  0x001B: { name: 'Battery Rated Capacity',         group: 'Battery Config', scale: 0.1, unit: 'Ah' },
  0x001C: { name: 'Battery Current Capacity',         group: 'Battery Config', scale: 0.1, unit: 'Ah' },
  0x001D: { name: 'Battery Calc Capacity',         group: 'Battery Config', scale: 0.1, unit: 'Ah' },
  0x001E: { name: 'Battery Discharge Capacity',         group: 'Battery Config', scale: 0.1, unit: 'Ah' },
  0x001F: { name: 'Battery Cycle Count',         group: 'Battery Config', scale: 1,   unit: 'cyc' },
  // ── Config 0x20-0x2E ────────────────────────
  0x0020: { name: 'PV Input Min Voltage',       group: 'PV Config',   scale: 0.1, unit: 'V' },
  0x0021: { name: 'PV Input Max Voltage',       group: 'PV Config',   scale: 0.1, unit: 'V' },
  0x0022: { name: 'Charge Equalize Voltage',       group: 'PV Config',   scale: 1,   unit: 'mV' },
  0x0023: { name: 'Charge Float Voltage',       group: 'PV Config',   scale: 1,   unit: 'mV' },
  0x0024: { name: 'AC Charge Power',     group: 'PV Config',   scale: 1,   unit: 'W' },
  0x0025: { name: 'PV Charge Power',     group: 'PV Config',   scale: 1,   unit: 'W' },
  0x0026: { name: 'AC+PV Charge Power',group: 'PV Config',   scale: 1,   unit: 'W' },
  0x002B: { name: 'Battery Rated Capacity (2)',      group: 'Battery Config', scale: 0.1, unit: 'Ah' },
  0x002C: { name: 'Charge Total Time',         group: 'Battery Config', scale: 1,   unit: 'h' },
  0x002D: { name: 'Discharge Total Time',         group: 'Battery Config', scale: 1,   unit: 'h' },
  0x002E: { name: 'Re-Wake After Full',       group: 'Battery Config', scale: 1,   unit: 'h' },
  0x0054: { name: 'PV/Battery Priority Min SOC', group: 'Battery Config', scale: 1, unit: '%' },
  0x0085: { name: 'AC Realtime Charge Power',   group: 'PV Config',   scale: 1,   unit: 'W' },
  0x0086: { name: 'PV/Battery Priority',        group: 'Mode/Version',
            fmt: (raw) => raw === 0x01AA ? 'Enabled' : raw === 0xAA01 ? 'Disabled' : `0x${raw.toString(16).toUpperCase()}` },
  // ── Status 0x100-0x107 ──────────────────────
  0x0100: { name: 'AC Input Voltage',         group: 'AC Live',   scale: 0.1, unit: 'V' },
  0x0101: { name: 'AC Input Frequency',         group: 'AC Live',   scale: 0.1, unit: 'Hz' },
  0x0102: { name: 'AC Output Voltage',         group: 'AC Live',   scale: 0.1, unit: 'V' },
  0x0103: { name: 'AC Output Frequency',         group: 'AC Live',   scale: 0.1, unit: 'Hz' },
  0x0104: { name: 'AC Output Power',         group: 'AC Live',   scale: 1,   unit: 'W' },
  0x0105: { name: 'PV Input Voltage',           group: 'PV Live',   scale: 0.1, unit: 'V' },
  0x0106: { name: 'PV Charge Power',           group: 'PV Live',   scale: 1,   unit: 'W' },
  0x0107: { name: 'AC Charge Power',         group: 'AC Live',   scale: 1,   unit: 'W' },
  // ── Cell voltages 0x108-0x118 ───────────────
  0x0108: { name: 'Cell 1 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0109: { name: 'Cell 2 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x010A: { name: 'Cell 3 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x010B: { name: 'Cell 4 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x010C: { name: 'Cell 5 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x010D: { name: 'Cell 6 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x010E: { name: 'Cell 7 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x010F: { name: 'Cell 8 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0110: { name: 'Cell 9 Voltage',        group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0111: { name: 'Cell 10 Voltage',       group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0112: { name: 'Cell 11 Voltage',       group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0113: { name: 'Cell 12 Voltage',       group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0114: { name: 'Cell 13 Voltage',       group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0115: { name: 'Cell 14 Voltage',       group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0116: { name: 'Cell 15 Voltage',       group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0117: { name: 'Cell 16 Voltage',       group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  0x0118: { name: 'Cell Cap Voltage',     group: 'Cell Voltage', scale: 1,   unit: 'mV' },
  // ── Cell stats 0x119-0x11F ──────────────────
  0x0119: { name: 'Cell Capacity',             group: 'Battery Live', scale: 0.1, unit: 'Ah' },
  0x011A: { name: 'Cell SOC',         group: 'Battery Live', scale: 0.1, unit: '%' },
  0x011B: { name: 'Cell Cycle Count',   group: 'Battery Live', scale: 1,   unit: 'cyc' },
}
