/**
 * Onboarding, run once after a first sign-up (PRD §4.7.3).
 *
 * Two steps, both straight off the handoff:
 *   A_2.2.1_Onboarding_Name    — "What should we call you?"
 *   A_2.2.2_Onboarding_Device  — add the first device, or skip
 *
 * The name step was removed in v4.1.4, which unified the display name to the
 * registration account. That account is an autogenerated local-part, not
 * something anyone chose, so the name is asked for again here and becomes both
 * the name the app shows and the name on the account.
 */
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import Icon from '../components/Icon'
import TextField from '../components/TextField'
import BottomAction from '../components/BottomAction'
import ProvisioningPage from './ProvisioningPage'
import { useAuthStore } from '../stores/authStore'
import { getUserProfile, saveUserProfile } from '../db/powerflowDB'
import { updateUserInfo } from '../api/authApi'
import { isApiSuccess } from '../utils/apiClient'
import { toast } from '../components/Toast'

type Step = 'name' | 'device'

export default function OnboardingPage() {
  const navigate = useNavigate()
  const authUser = useAuthStore((s) => s.user)
  const account = authUser?.account ?? ''

  const [step, setStep] = useState<Step>('name')
  const [name, setName] = useState('')
  const [saving, setSaving] = useState(false)
  const [showProvisioning, setShowProvisioning] = useState(false)

  const finish = () => navigate('/devices', { replace: true })

  /**
   * The name is written to this account's cached profile first, because that is
   * what Settings and Profile read and it cannot fail. The account name is
   * then updated on the server; if that is rejected the step still completes —
   * onboarding must not dead-end on a backend error — but the failure is
   * surfaced rather than swallowed, which is how the rename bug stayed
   * invisible the last time this screen existed.
   */
  const saveName = async () => {
    const trimmed = name.trim()
    if (!trimmed || saving) return
    setSaving(true)
    try {
      const existing = await getUserProfile(account)
      await saveUserProfile(account, {
        name: trimmed,
        email: existing?.email ?? authUser?.email ?? account,
        avatar: existing?.avatar ?? null,
        memberSince: existing?.memberSince ?? new Date().toISOString().slice(0, 10),
        updatedAt: Date.now(),
      })
    } catch (err) {
      console.error('[Onboarding] could not cache the name:', err)
    }
    try {
      const r = await updateUserInfo({ name: trimmed })
      if (!isApiSuccess(r.code)) {
        toast.info("Saved on this phone — we couldn't update the name on your account.")
      }
    } catch {
      toast.info("Saved on this phone — we couldn't update the name on your account.")
    }
    setSaving(false)
    setStep('device')
  }

  // ─── Add Device flow (BLE provisioning) ──────────────────────────────────
  if (showProvisioning) {
    return <ProvisioningPage onClose={finish} />
  }

  // ─── Step 1: what should we call you (A_2.2.1) ────────────────────────────
  if (step === 'name') {
    return (
      <div className="h-full flex flex-col bg-ink-12">
        {/* 4x export A_2.2.1: header box 80, headline headline_medium at y155,
            subtitle body_medium/ink-5, the 68px field at y228 and the action bar
            hairline at y470. */}
        <div className="px-4 pb-5 safe-area-top-header flex items-center">
          <button
            onClick={finish}
            aria-label="Skip"
            className="relative w-10 h-10 rounded-full bg-ink-9 flex items-center justify-center before:absolute before:content-[''] before:-inset-1"
          >
            <Icon name="chevron-left" size={24} />
          </button>
        </div>

        <div className="flex-1 min-h-0 px-4">
          <h1 className="mt-4 text-headline-md font-semibold text-white text-center">
            What should we call you?
          </h1>
          <p className="mt-2 text-body-md text-ink-5 text-center">
            Help personalize your Sierro experience.
          </p>
          <div className="mt-6">
            <TextField
              ariaLabel="Your name"
              value={name}
              onChange={setName}
              onClear={() => setName('')}
              placeholder="Your name"
              maxLength={40}
              autoFocus
            />
          </div>
        </div>

        <BottomAction
          label="Continue"
          onPress={() => { void saveName() }}
          disabled={!name.trim()}
          busy={saving}
        />
      </div>
    )
  }

  // ─── Step 2: add the first device (A_2.2.2) ───────────────────────────────
  return (
    <div className="h-full flex flex-col bg-ink-12">
      {/* 4x export A_2.2.2: header box 80, title title_large/ink-3 at y154, subtitle
          body_medium/ink-5, illustration 264 wide at y312, ink-9 hairline at y769 and a
          370x44 filled button (radius m, primary-darker label) at y781. */}
      <div className="px-4 pb-5 safe-area-top-header flex items-center justify-between">
        <button
          onClick={() => setStep('name')}
          aria-label="Back"
          className="relative w-10 h-10 rounded-full bg-ink-9 flex items-center justify-center before:absolute before:content-[''] before:-inset-1"
        >
          <Icon name="chevron-left" size={24} />
        </button>
        <button onClick={finish} className="text-body-md text-primary active:opacity-70">
          Skip for now
        </button>
      </div>

      <div className="flex-1 flex flex-col items-center px-6 text-center">
        <h1 className="mt-[18px] text-title-lg font-semibold text-ink-3">Add Your First Device</h1>
        <p className="mt-3 text-body-md text-ink-5">
          We&apos;ll help you find and connect your Sierro device in a few simple steps.
        </p>
        {/* Cropped out of A_2.2.2 at 3x. The old ds-onboarding.svg wrapped a 400px
            raster and was drawn 300 wide, so a 3x phone upscaled it 2.25x — which
            is why it looked soft. 264 wide, centred on the frame the way the
            handoff has it. */}
        <img
          src={`${import.meta.env.BASE_URL}ds-onboarding-device.png`}
          alt=""
          width={264}
          height={250}
          className="mt-[90px] w-[264px] max-w-full h-auto select-none"
          draggable={false}
        />
      </div>

      <BottomAction label="Connect Device" onPress={() => setShowProvisioning(true)} />
    </div>
  )
}
