/**
 * The founding-member roster.
 *
 * Onboarding shows the Founding Member screen when the address the account was
 * registered with is on the list, and the number beside it is the one printed
 * on the badge — a real place in the order people joined, not something
 * generated at runtime. The redeem-code path in Settings (`activateFounderBadge`)
 * invents a number from the clock and so can hand two people the same badge;
 * this cannot.
 *
 * ADDRESSES ARE NOT STORED. The roster ships inside the app, and the app ships
 * to anyone who wants it, so a readable list would hand whoever unpacks the
 * bundle every VIP customer's email. What ships is the SHA-256 of each
 * normalised address (src/data/foundingMemberRoster.ts, generated by
 * scripts/build_founding_roster.py from the VIP workbook); the address of
 * whoever signs in is hashed the same way and looked up. Someone can still test
 * an address they already know — hashing cannot prevent that — but the list can
 * no longer be READ OUT, which is the exposure that matters.
 *
 * There is no endpoint for this yet. When one exists, `foundingMemberNumber` is
 * the only thing that answers the question, so it is the only thing that has to
 * change.
 */
import { FOUNDING_MEMBER_HASHES } from './foundingMemberRoster'

/**
 * Lowercased and trimmed; '' for anything that is not a usable address.
 *
 * Must stay identical to `normalise()` in scripts/build_founding_roster.py, or
 * the hashes it generates stop matching the ones computed here. Nothing beyond
 * case and space is touched: Gmail treats `a.b@` and `ab@` as one address and
 * this does not, so the sheet has to carry the address people actually
 * registered with.
 */
export function normalizeEmail(raw: string | null | undefined): string {
  if (typeof raw !== 'string') return ''
  return raw.trim().toLowerCase()
}

/** Lowercase hex SHA-256, or null where the platform will not hash. */
async function sha256Hex(value: string): Promise<string | null> {
  const subtle = globalThis.crypto?.subtle
  if (!subtle) {
    // Only reachable in an insecure context. Failing closed is the right way
    // round: nobody gets a badge, rather than the wrong person getting one.
    console.warn('[foundingMembers] no WebCrypto here; cannot check the roster')
    return null
  }
  const bytes = new TextEncoder().encode(value)
  const digest = await subtle.digest('SHA-256', bytes)
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

/** One hash per address per session; onboarding asks more than once. */
const cache = new Map<string, number | null>()

/**
 * The member's number, or null if this address is not a founding member.
 *
 * A number rather than a boolean because every caller needs it: the screen
 * prints it and the badge stores it.
 */
export async function foundingMemberNumber(
  email: string | null | undefined,
): Promise<number | null> {
  const key = normalizeEmail(email)
  if (!key) return null
  const cached = cache.get(key)
  if (cached !== undefined) return cached

  const hash = await sha256Hex(key)
  // `typeof === 'number'` and not a truthiness check: a plain-object lookup
  // answers inherited keys like 'toString' with a function, and anything
  // truthy there would put a stranger on the screen wearing someone's badge.
  const raw = hash ? FOUNDING_MEMBER_HASHES[hash] : undefined
  const number = typeof raw === 'number' && Number.isFinite(raw) ? raw : null

  // A platform that cannot hash is a temporary condition, not an answer.
  if (hash) cache.set(key, number)
  return number
}

export async function isFoundingMember(email: string | null | undefined): Promise<boolean> {
  return (await foundingMemberNumber(email)) !== null
}

/** Addresses on the roster — more than the member count, since some have two. */
export function foundingMemberAddressCount(): number {
  return Object.keys(FOUNDING_MEMBER_HASHES).length
}

/** People on the roster. */
export function foundingMemberCount(): number {
  return new Set(Object.values(FOUNDING_MEMBER_HASHES)).size
}

/** The generated table, for the test that keeps it honest. */
export function foundingMemberEntries(): ReadonlyArray<readonly [string, number]> {
  return Object.entries(FOUNDING_MEMBER_HASHES)
}
